### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/ivre/geoip/GeoLite2-City.dump-IPv4.csv'

### ISSUE THREAD

**Issue by MarcinK50** [cea-sec/ivre#1030]
Please try to follow this template. Also, please format your issue
properly (particularly to report code or command line output). You may
want to read
[Github's basic writing and formatting syntax](https://help.github.com/articles/basic-writing-and-formatting-syntax/).

### IVRE Version

```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.15

Python 3.8.4 (default, Jul 13 2020, 21:16:07) 
[GCC 9.3.0]Insert here the output of the command `ivre version`, displayed as
code. For example:

Linux kali 5.7.0-kali1-amd64 #1 SMP Debian 5.7.6-1kali2 (2020-07-01) x86_64

Dependencies:
    Python module pymongo: 3.11.0
    Python module py2neo: 3.1.2
    Python module sqlalchemy: 1.3.18
    Python module psycopg2: 2.8.5 (dt dec pq3 ext lo64)
    Python module cryptography: 2.8
    Python module krbV: missing
    Python module PIL: 6.2.1
    Python module MySQLdb: 1.4.4
    Python module dbus: 1.2.16
    Python module matplotlib: 3.2.2
    Python module bottle: 0.12.15
    Python module OpenSSL: 19.1.0
    Python module tinydb: 3.15.2

```

### Summary

```ivre runscans --country PL``` not working.

### Expected behavior

Scan the network devices

### Actual behavior

crash
```shell
Traceback (most recent call last):
  File "/usr/bin/ivre", line 88, in <module>
    main()
  File "/usr/bin/ivre", line 60, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/lib/python3/dist-packages/ivre/tools/runscans.py", line 351, in main
    targets = ivre.target.target_from_args(args)
  File "/usr/lib/python3/dist-packages/ivre/target.py", line 489, in target_from_args
    target = TargetCity(args.city[0], args.city[1],
  File "/usr/lib/python3/dist-packages/ivre/target.py", line 215, in __init__
    geoiputils.get_ranges_by_city(country_code, city), rand=rand,
  File "/usr/lib/python3/dist-packages/ivre/geoiputils.py", line 354, in get_ranges_by_city
    return get_ranges_by_data(
  File "/usr/lib/python3/dist-packages/ivre/geoiputils.py", line 334, in get_ranges_by_data
    for start, stop in _get_by_data(datafile, condition):
  File "/usr/lib/python3/dist-packages/ivre/geoiputils.py", line 325, in _get_by_data
    fdesc = open(os.path.join(config.GEOIP_PATH, datafile))
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/ivre/geoip/GeoLite2-City.dump-IPv4.csv'
```

### How to reproduce

```ivre runscans --country PL```

### More

I'm using IVRE first time, so i can do something wrong :D.

**Comment by p-l-** [comment]
You need to install and setup IVRE properly before you can use it. Particularly, you should run `ivre ipdata --download --import-all`.

**Comment by MarcinK50** [comment]
Thanks!
