### ISSUE TITLE
IVRE + Elasticsearch

### ISSUE THREAD

**Issue by ubushan** [cea-sec/ivre#1032]
```
ivre --version
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.15

Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0]

Linux IVRE 5.4.0-1031-azure #32-Ubuntu SMP Tue Oct 6 09:47:33 UTC 2020 x86_64

Dependencies:
    Python module pymongo: 3.7.2
    Python module py2neo: missing
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module cryptography: 3.2.1
    Python module krbV: missing
    Python module PIL: 8.0.1
    Python module MySQLdb: missing
    Python module dbus: 1.2.16
    Python module matplotlib: missing
    Python module bottle: 0.12.19
    Python module OpenSSL: 19.1.0
    Python module tinydb: missing
```

Hello! I have a problem with IVRE+Elasticsearh. Yesterday and later I didn't have this issue and it worked, but after today's scan, new results are not record to Elasticsearch index. I did regular active scan via nmap `ivre runscan ...`.
Why is this happening?
Thanks.

```
IVRE_CONF=~/.ivre-elastic.conf ivre db2view --no-merge --verbose nmap
WARNING:elasticsearch:POST http://127.0.0.1:9992/ivre-views/_doc [status:400 request:0.135s]
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 88, in <module>
    main()
  File "/usr/local/bin/ivre", line 60, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.8/dist-packages/ivre/tools/db2view.py", line 136, in main
    output(elt)
  File "/usr/local/lib/python3.8/dist-packages/ivre/db/elastic.py", line 257, in store_host
    self.db_client.index(index=self.indexes[0],
  File "/home/azureuser/.local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/azureuser/.local/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 398, in index
    return self.transport.perform_request(
  File "/home/azureuser/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/home/azureuser/.local/lib/python3.8/site-packages/elasticsearch/transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/home/azureuser/.local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/azureuser/.local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 312, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', "failed to parse field [ports.scripts.ssl-cert.pubkey.exponent] of type [long] in document with id 'nnq85HUBJ_rn6ccOS0wY'. Preview of field's value: 'userdata: 0x5578b80009f8'")
```

**Comment by ubushan** [comment]
Without option `--no-merge`. But
```
IVRE_CONF=~/.ivre-elastic.conf ivre db2view --verbose nmap
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 88, in <module>
    main()
  File "/usr/local/bin/ivre", line 60, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.8/dist-packages/ivre/tools/db2view.py", line 136, in main
    output(elt)
  File "/usr/local/lib/python3.8/dist-packages/ivre/db/elastic.py", line 1127, in store_or_merge_host
    if not self.merge_host(host):
  File "/usr/local/lib/python3.8/dist-packages/ivre/db/__init__.py", line 2266, in merge_host
    self.store_host(self.merge_host_docs(rec, host))
  File "/usr/local/lib/python3.8/dist-packages/ivre/db/__init__.py", line 2116, in merge_host_docs
    raise ValueError("Cannot merge host documents. "
ValueError: Cannot merge host documents. Schema versions differ (18 != 16)
```

I ran this command `sudo ivre view --update-schema` but for some reason it only updates to version 16 of the scheme. Why?
But should it be version 18?
```
INFO:ivre:Migrating column 0 from version None to 1
INFO:ivre:Creating new indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version None to 1 DONE
INFO:ivre:Migrating column 0 from version 1 to 2
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 1 to 2 DONE
INFO:ivre:Migrating column 0 from version 2 to 3
INFO:ivre:Creating new indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 2 to 3 DONE
INFO:ivre:Migrating column 0 from version 3 to 4
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 3 to 4 DONE
INFO:ivre:Migrating column 0 from version 4 to 5
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 4 to 5 DONE
INFO:ivre:Migrating column 0 from version 5 to 6
INFO:ivre:Creating new indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 5 to 6 DONE
INFO:ivre:Migrating column 0 from version 6 to 7
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 6 to 7 DONE
INFO:ivre:Migrating column 0 from version 7 to 8
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 7 to 8 DONE
INFO:ivre:Migrating column 0 from version 8 to 9
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 8 to 9 DONE
INFO:ivre:Migrating column 0 from version 9 to 10
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 9 to 10 DONE
INFO:ivre:Migrating column 0 from version 10 to 11
INFO:ivre:Creating new indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 10 to 11 DONE
INFO:ivre:Migrating column 0 from version 11 to 12
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 11 to 12 DONE
INFO:ivre:Migrating column 0 from version 12 to 13
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 12 to 13 DONE
INFO:ivre:Migrating column 0 from version 13 to 14
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 13 to 14 DONE
INFO:ivre:Migrating column 0 from version 14 to 15
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 14 to 15 DONE
INFO:ivre:Migrating column 0 from version 15 to 16
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 15 to 16 DONE
```

And also I ran this command `IVRE_CONF=~/.ivre-elastic.conf ivre view --update-schema` , but also without result and without output.

`ElasticSearch v 7.9.1`

**Comment by p-l-** [comment]
Hi,

The Elasticsearch backend is **very** experimental. It does not know how to migrate documents between different schema versions. So you need to clean (`ivre view --init`) the view and build it again.

**Comment by ubushan** [comment]
Did not help.
I ran this commands
```
ivre view --init
IVRE_CONF=~/.ivre-elastic.conf ivre db2view

Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 88, in <module>
    main()
  File "/usr/local/bin/ivre", line 60, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.8/dist-packages/ivre/tools/db2view.py", line 136, in main
    output(elt)
  File "/usr/local/lib/python3.8/dist-packages/ivre/db/elastic.py", line 1127, in store_or_merge_host
    if not self.merge_host(host):
  File "/usr/local/lib/python3.8/dist-packages/ivre/db/__init__.py", line 2266, in merge_host
    self.store_host(self.merge_host_docs(rec, host))
  File "/usr/local/lib/python3.8/dist-packages/ivre/db/__init__.py", line 2116, in merge_host_docs
    raise ValueError("Cannot merge host documents. "
ValueError: Cannot merge host documents. Schema versions differ (18 != 16)
```
After I update schema, but it not fix my problem=(
```
$ ivre view --update-schema
INFO:ivre:Migrating column 0 from version None to 1
INFO:ivre:Creating new indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version None to 1 DONE
INFO:ivre:Migrating column 0 from version 1 to 2
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 1 to 2 DONE
INFO:ivre:Migrating column 0 from version 2 to 3
INFO:ivre:Creating new indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 2 to 3 DONE
INFO:ivre:Migrating column 0 from version 3 to 4
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 3 to 4 DONE
INFO:ivre:Migrating column 0 from version 4 to 5
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 4 to 5 DONE
INFO:ivre:Migrating column 0 from version 5 to 6
INFO:ivre:Creating new indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 5 to 6 DONE
INFO:ivre:Migrating column 0 from version 6 to 7
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 6 to 7 DONE
INFO:ivre:Migrating column 0 from version 7 to 8
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 7 to 8 DONE
INFO:ivre:Migrating column 0 from version 8 to 9
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 8 to 9 DONE
INFO:ivre:Migrating column 0 from version 9 to 10
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 9 to 10 DONE
INFO:ivre:Migrating column 0 from version 10 to 11
INFO:ivre:Creating new indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 10 to 11 DONE
INFO:ivre:Migrating column 0 from version 11 to 12
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 11 to 12 DONE
INFO:ivre:Migrating column 0 from version 12 to 13
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 12 to 13 DONE
INFO:ivre:Migrating column 0 from version 13 to 14
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 13 to 14 DONE
INFO:ivre:Migrating column 0 from version 14 to 15
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 14 to 15 DONE
INFO:ivre:Migrating column 0 from version 15 to 16
INFO:ivre:Migrating records...
INFO:ivre:  ... Done.
INFO:ivre:  Performing other actions on indexes...
INFO:ivre:  ... Done.
INFO:ivre:Migration of column 0 from version 15 to 16 DONE

$ IVRE_CONF=~/.ivre-elastic.conf ivre db2view
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 88, in <module>
    main()
  File "/usr/local/bin/ivre", line 60, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.8/dist-packages/ivre/tools/db2view.py", line 136, in main
    output(elt)
  File "/usr/local/lib/python3.8/dist-packages/ivre/db/elastic.py", line 1127, in store_or_merge_host
    if not self.merge_host(host):
  File "/usr/local/lib/python3.8/dist-packages/ivre/db/__init__.py", line 2266, in merge_host
    self.store_host(self.merge_host_docs(rec, host))
  File "/usr/local/lib/python3.8/dist-packages/ivre/db/__init__.py", line 2116, in merge_host_docs
    raise ValueError("Cannot merge host documents. "
ValueError: Cannot merge host documents. Schema versions differ (18 != 16)
```
How update the schema to version 18?

**Comment by p-l-** [comment]
You are not using the same config for both of your commands! Try this:
```
$ IVRE_CONF=~/.ivre-elastic.conf ivre view --init
$ IVRE_CONF=~/.ivre-elastic.conf ivre db2view
```

**Comment by ubushan** [comment]
`$ IVRE_CONF=~/.ivre-elastic.conf ivre view --init` Is this the command to initialize the index? It will delete all data from the index. and we need this information.

**Comment by p-l-** [comment]
Elasticsearch **cannot** migrate data from one schema version to another. It is an **experimental** backend. You can either keep the old version of IVRE that inserted the documents **or** remove the view **and** insert the create the view again with a newer version of IVRE.
