### ISSUE TITLE
Problems with passiverecn ( p0f )

### ISSUE THREAD

**Issue by fjavierc** [cea-sec/ivre#171]
Hi guys;

I'm starting to use the features of passive recon but I have problems using p0f.

I'm using p0f 2.0.8 and Debian 8.2
```
root@Quijote:/tmp# apt-cache showpkg p0f
Package: p0f
Versions: 
2.0.8-2 (/var/lib/apt/lists/ftp.es.debian.org_debian_dists_jessie_main_binary-amd64_Packages) (/var/lib/dpkg/status)
```

If I run p0f and read a pcap file, i get information about fingerprints:
```
root@Quijote:/tmp# p0f -s /tmp/demo | more
p0f - passive os fingerprinting utility, version 2.0.8
(C) M. Zalewski <lcamtuf@dione.cc>, W. Stearns <wstearns@pobox.com>
p0f: listening (SYN) on '/tmp/demo', 262 sigs (14 generic, cksum 0F1F5CA2), rule: 'all'.
85.XXX.XXX.201:1122 - Windows XP SP1+, 2000 SP3 (2) [priority1] 
  -> 10.302.404.503:443 (distance 21, link: sometimes DSL (3))
```

But when I run p0fdb with a pcap file, it gives me the following error:
```
root@Quijote:/tmp# p0f2db --sensor QUIJOTE-PASIVO /tmp/demo 

p0f - passive os fingerprinting utility, version 2.0.8
(C) M. Zalewski <lcamtuf@dione.cc>, W. Stearns <wstearns@pobox.com>
p0f: listening (SYN) on '/tmp/demo', 262 sigs (14 generic, cksum 0F1F5CA2), rule: 'tcp and tcp[tcpflags] & (tcp-syn|tcp-ack) == 2'.

Traceback (most recent call last):
  File "/usr/local/bin/p0f2db", line 100, in <module>
    process_file(filename, args.sensor, args.bulk, args.mode)
  File "/usr/local/bin/p0f2db", line 67, in process_file
    ) for line in p0fprocess.stdout
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 670, in insert_or_update_bulk
    self.insert_or_update(timestamp, spec, getinfos=getinfos)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/mongo.py", line 2554, in insert_or_update
    upsert=True,
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 572, in update
    check_keys, self.uuid_subtype), safe)
  File "/usr/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 1124, in _send_message
    rv = self.__check_response_to_last_error(response, command)
  File "/usr/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 1066, in __check_response_to_last_error
    raise OperationFailure(details["err"], code, result)
pymongo.errors.OperationFailure: Invalid modifier specified $min

root@Quijote:/tmp# [+] End of input file.
```

I know very little about python and mongo and would appreciate any help. Any idea?

Thank you.

**Comment by p-l-** [comment]
Hi,

Thanks for reporting this. Which version of MongoDB and pymongo are you using?

**Comment by fjavierc** [comment]
Hi Pierre;

```
root@Quijote:~# dpkg -l | grep mongo
ii  mongodb                               1:2.4.10-5                           amd64        object/document-oriented database (metapackage)
ii  mongodb-clients                       1:2.4.10-5                           amd64        object/document-oriented database (client apps)
ii  mongodb-dev                           1:2.4.10-5                           amd64        object/document-oriented database (development)
ii  mongodb-server                        1:2.4.10-5                           amd64        object/document-oriented database (server package)
ii  python-pymongo                        2.7.2-1                              amd64        Python interface to the MongoDB document-oriented database
ii  python-pymongo-ext                    2.7.2-1                              amd64        C-coded extension to the python-pymongo package
```

Thanks and sorry my poor English ( in Spanish is more easy for me ;-)  )

**Comment by p-l-** [comment]
MongoDB 2.4 is not supported in IVRE, 2.6 is the minimum version.

Can you upgrade and tell us if that fixes your issue (I think it will).

Don't worry about the English, the main point is to be understood, and you are!

**Comment by fjavierc** [comment]
Yeah !! Solved !!

I read the documentation very fast and I did not notice that detail ( FAST-INSTALL-AND-FIRST-RUN.md and INSTALL.md mentions MongoDB 2.6 minimum... agghhh!! )

Not only solved my problem with p0f2db, also fixes my problem with Bro ( not recorded nothing and I don't have any error message about it ), if it is also of interest :-)

Now: 

```
root@Quijote:~# p0f2db --sensor QUIJOTE-PASIVO /tmp/demo
p0f - passive os fingerprinting utility, version 2.0.8
(C) M. Zalewski <lcamtuf@dione.cc>, W. Stearns <wstearns@pobox.com>
p0f: listening (SYN) on '/tmp/demo', 262 sigs (14 generic, cksum 0F1F5CA2), rule: 'tcp and tcp[tcpflags] & (tcp-syn|tcp-ack) == 2'.
[+] End of input file.
```

... and if query:

```
root@Quijote:~# ipinfo
10.302.404.501 	P0F2-SYN Windows 2000 SP4, XP SP1+ [priority1] [*:121:1:48:M1460,N,N,S:.] at 7 hops (1 time) 2015-10-30 07:18:27 - 2015-10-30 07:18:27 QUIJOTE-PASIVO
10.302.400.502 	P0F2-SYN Windows XP/2000 (RFC1323+, w+, tstamp-) [GENERIC] [*:126:1:52:M1460,N,W8,N,N,S:.] at 2 hops (1 time) 2015-10-30 07:18:27 - 2015-10-30 07:18:27 QUIJOTE-PASIVO
10.302.402.503 	P0F2-SYN Windows 2000 SP2+, XP SP1+ (seldom 98) [priority1] [*:114:1:48:M1460,N,N,S:.] at 14 hops (1 time) 2015-10-30 07:18:27 - 2015-10-30 07:18:27 QUIJOTE-PASIVO
...
```

What I do:
```
root@Quijote:~# apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10

root@Quijote:~# echo "deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.0 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list

root@Quijote:~# apt-get update
....

root@Quijote:~# apt-cache showpkg mongodb-org
Package: mongodb-org
Versions: 
3.0.7 (/var/lib/apt/lists/repo.mongodb.org_apt_debian_dists_wheezy_mongodb-org_3.0_main_binary-amd64_Packages)
...

root@Quijote:~# apt-get install mongodb-org    # ¡¡¡¡ This uninstall mongodb 2.4 and install mongodb 3.0.7 !!!
...
Se instalarán los siguientes paquetes extras:
  mongodb-org-mongos mongodb-org-server mongodb-org-shell mongodb-org-tools
Los siguientes paquetes se ELIMINARÁN:
  mongodb mongodb-clients mongodb-dev mongodb-server
Se instalarán los siguientes paquetes NUEVOS:
  mongodb-org mongodb-org-mongos mongodb-org-server mongodb-org-shell mongodb-org-tools
0 actualizados, 5 nuevos se instalarán, 4 para eliminar y 0 no actualizados.
....

root@Quijote:~# dpkg -l | grep mongo
ii  mongodb-org                           3.0.7                                amd64        MongoDB open source document-oriented database system (metapackage)
ii  mongodb-org-mongos                    3.0.7                                amd64        MongoDB sharded cluster query router
ii  mongodb-org-server                    3.0.7                                amd64        MongoDB database server
ii  mongodb-org-shell                     3.0.7                                amd64        MongoDB shell client
ii  mongodb-org-tools                     3.0.7                                amd64        MongoDB tools
rc  mongodb-server                        1:2.4.10-5                           amd64        object/document-oriented database (server package)
ii  python-pymongo                        2.7.2-1                              amd64        Python interface to the MongoDB document-oriented database
ii  python-pymongo-ext                    2.7.2-1                              amd64        C-coded extension to the python-pymongo package
```

I'm using Debian 8.2 and follow the guide http://docs.mongodb.org/manual/tutorial/install-mongodb-on-debian/ ( appears on IVRE doc,  FAST-INSTALL-AND-FIRST-RUN.md ). Although MongoDB says it is for Wheezy, I have applied on Jessie


Thanks Pierre !!

**Comment by p-l-** [comment]
Great! I'm closing this issue but your comment will still be there for people running into the same problem. So, thanks for this comprehensive report.
