### ISSUE TITLE
Remove Agent

### ISSUE THREAD

**Issue by ltiisidii** [cea-sec/ivre#221]
Which is the command I should run to remove an agent (that I see when I run: ivre runscansagentdb --list-agents)

**Comment by p-l-** [comment]
Hi,

For now, you can use the Python API (there is no `--del-agent` option to `ivre runscansagentdb`): `ivre.db.db.agent.del_agent([agentid])`.

As this is not convenient, I'm submitting a PR to implement `--del-agent`.

**Comment by p-l-** [comment]
Can you check if the code from PR #222 works for you? Thanks!

**Comment by ltiisidii** [comment]
I tried the following, but without result (???????? <<-- is issue.net of ssh service of the agent)

 ivre runscansagentdb --del-agent 57090568af18cd523a3f9587
????????Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 71, in <module>
    main()
  File "/usr/local/bin/ivre", line 49, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscansagentdb.py", line 174, in main
    ivre.db.db.agent.del_agent(ivre.db.db.agent.str2id(agentid))
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1040, in del_agent
    self.sync(agentid)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 934, in sync
    scan = self.get_scan(self.str2id(scanid))
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1068, in get_scan
    scan['target'] = pickle.loads(scan['target'])
TypeError: 'NoneType' object has no attribute '__getitem__'

 ivre runscansagentdb --del-agent [57090568af18cd523a3f9587]
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 71, in <module>
    main()
  File "/usr/local/bin/ivre", line 49, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscansagentdb.py", line 174, in main
    ivre.db.db.agent.del_agent(ivre.db.db.agent.str2id(agentid))
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/mongo.py", line 294, in str2id
    return bson.ObjectId(string)
  File "/usr/local/lib/python2.7/dist-packages/bson/objectid.py", line 110, in __init__
    self.__validate(oid)
  File "/usr/local/lib/python2.7/dist-packages/bson/objectid.py", line 206, in __validate
    _raise_invalid_id(oid)
  File "/usr/local/lib/python2.7/dist-packages/bson/objectid.py", line 52, in _raise_invalid_id
    " or a 24-character hex string" % oid)
bson.errors.InvalidId: '[57090568af18cd523a3f9587]' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string

ivre runscansagentdb --del-agent AGENT 57090568af18cd523a3f9587
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 71, in <module>
    main()
  File "/usr/local/bin/ivre", line 49, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscansagentdb.py", line 174, in main
    ivre.db.db.agent.del_agent(ivre.db.db.agent.str2id(agentid))
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/mongo.py", line 294, in str2id
    return bson.ObjectId(string)
  File "/usr/local/lib/python2.7/dist-packages/bson/objectid.py", line 110, in __init__
    self.__validate(oid)
  File "/usr/local/lib/python2.7/dist-packages/bson/objectid.py", line 206, in __validate
    _raise_invalid_id(oid)
  File "/usr/local/lib/python2.7/dist-packages/bson/objectid.py", line 52, in _raise_invalid_id
    " or a 24-character hex string" % oid)
bson.errors.InvalidId: 'AGENT' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string

**Comment by p-l-** [comment]
Only the first one is supposed to work. Do you have a file from a previous scan in your directory? I don't understand why this error happens. Can you run a `find` in the agent directory and post the output?

**Comment by ltiisidii** [comment]
Output:

/var/lib/ivre/master/J7atFl# find
.
./input
./remote
./remote/input
./remote/output
./remote/output/57081085af18cd1fb941a606-4P7EDz.xml.bz2
./remote/output/5709058aaf18cd52485500eb-00J0vs.xml.bz2
./remote/output/57081085af18cd1fb941a606-jh2xRj.xml.bz2
./remote/output/5709058aaf18cd52485500eb-LrE2DS.xml.bz2
./remote/output/5709058aaf18cd52485500eb-Z6NqaY.xml.bz2
./remote/output/57081085af18cd1fb941a606-sjqIoj.xml.bz2
./remote/output/5709058aaf18cd52485500eb-wOrADY.xml.bz2
./remote/output/5709058aaf18cd52485500eb-Zq21pr.xml.bz2
./remote/output/5709058aaf18cd52485500eb-mgV17Y.xml.bz2
./remote/output/57081085af18cd1fb941a606-RvW00O.xml.bz2
./remote/output/57081085af18cd1fb941a606-UopJDb.xml.bz2
./remote/output/5709058aaf18cd52485500eb-VHLYYQ.xml.bz2
./remote/output/57081085af18cd1fb941a606-z9aeD9.xml.bz2
./remote/output/5709058aaf18cd52485500eb-XcsQTR.xml.bz2
./remote/output/5709058aaf18cd52485500eb-MMIsmQ.xml.bz2
./remote/output/57081085af18cd1fb941a606-PrHrwA.xml.bz2
./remote/output/5709058aaf18cd52485500eb-Y5vRf6.xml.bz2
./remote/output/5709058aaf18cd52485500eb-1xOCl7.xml.bz2
./remote/output/5709058aaf18cd52485500eb-ZBT75b.xml.bz2
./remote/output/5709058aaf18cd52485500eb-PyoZwB.xml.bz2
./remote/cur
./remote/cur/5709058aaf18cd52485500eb-_qsd97.xml.bz2
./remote/cur/5709058aaf18cd52485500eb-_qsd97

**Comment by p-l-** [comment]
Can you try the first one (`ivre runscansagentdb --del-agent 57090568af18cd523a3f9587`) with the following line inserted in `/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py` before line 1068 (`scan['target'] = pickle.loads(scan['target'])`):
```Python
        print scanid, scan
```

And post the output here, please? Thanks!

**Comment by ltiisidii** [comment]
I don't have access to the slave agent, because i ended the contract with the vps provider.  (Because: "Suspension reason: 60+ nmap processes (CPU Load , portscanning/similar" ) <-- hehe LOL 

ivre runscansagentdb --del-agent 57090568af18cd523a3f9587
ssh: connect to host [redacted] port 22: Connection timed out
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.0]
ssh: connect to host [redacted] port 22: Connection timed out
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(226) [Receiver=3.1.0]
ssh: connect to host [redacted] port 22: Connection timed out
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(226) [Receiver=3.1.0]
ssh: connect to host [redacted] port 22: Connection timed out
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(226) [Receiver=3.1.0]
57081085af18cd1fb941a606 None
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 73, in <module>
    main()
  File "/usr/local/bin/ivre", line 51, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscansagentdb.py", line 174, in main
    ivre.db.db.agent.del_agent(ivre.db.db.agent.str2id(agentid))
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1045, in del_agent
    self.sync(agentid)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 939, in sync
    scan = self.get_scan(self.str2id(scanid))
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1075, in get_scan
    scan['target'] = pickle.loads(scan['target'])
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by p-l-** [comment]
Sorry for the delay. Did you remove the scan **before** trying to remove the agent?
