### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by powerhikki** [cea-sec/ivre#236]
Hi. After I started 
& sudo ivre runscans --routable --limit 1000
I get error:

```
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 71, in <module>
    main()
  File "/usr/local/bin/ivre", line 49, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscans.py", line 439, in main
    accept_target_status=accept_target_status)
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscans.py", line 190, in call_nmap
    stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
~$
```
Linux alex 2.6.32-042stab108.1 #1 SMP Thu Apr 23 19:17:11 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux

Python 2.7.6

db version v2.4.9
Wed Jun  8 13:46:20.241 git version: nogitversion

**Comment by fmonjalet** [comment]
Hi,

I would say that `nmap` is not installed or not in your `$PATH`. Could you check it is?

**Comment by powerhikki** [comment]
Ok, I reinstall nmap and scanning working now. 

Thanx.

**Comment by p-l-** [comment]
Thanks @fmonjalet!
