### ISSUE TITLE
ivre ipdata --import-all --no-update-passive-db fail 

### ISSUE THREAD

**Issue by nirhenn** [cea-sec/ivre#282]
ubuntu@ivre:~$ ivre scancli --init
This will remove any scan result in your database. Process ? [y/N] y
ubuntu@ivre:~$ ivre ipinfo --init
This will remove any passive information in your database. Process ? [y/N] y
ubuntu@ivre:~$ ivre ipdata --init
This will remove any country/AS information in your database. Process ? [y/N] y
ubuntu@ivre:~$ sudo ivre runscansagentdb --init
This will remove any agent and/or scan in your database and files. Process ? [y/N] y
ubuntu@ivre:~$ ivre ipdata --download
Downloading http://geolite.maxmind.com/download/geoip/database/GeoLiteCity_CSV/GeoLiteCity-latest.zip to /usr/local/share/ivre/geoip/GeoIPCityCSV.zip: Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 73, in <module>
    main()
  File "/usr/local/bin/ivre", line 51, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/ipdata.py", line 95, in main
    ivre.geoiputils.download_all(verbose=not args.quiet)
  File "/usr/local/lib/python2.7/dist-packages/ivre/geoiputils.py", line 152, in download_all
    with open(outfile, 'w') as wdesc:
IOError: [Errno 13] Permission denied: '/usr/local/share/ivre/geoip/GeoIPCityCSV.zip'
ubuntu@ivre:~$ sudo ivre ipdata --download
Downloading http://geolite.maxmind.com/download/geoip/database/GeoLiteCity_CSV/GeoLiteCity-latest.zip to /usr/local/share/ivre/geoip/GeoIPCityCSV.zip: 
done.
Downloading http://thyme.apnic.net/current/data-raw-table to /usr/local/share/ivre/geoip/BGP.raw: done.
Downloading http://geolite.maxmind.com/download/geoip/database/asnum/GeoIPASNum2.zip to /usr/local/share/ivre/geoip/GeoIPASNumCSV.zip: done.
Downloading http://geolite.maxmind.com/download/geoip/database/GeoIPCountryCSV.zip to /usr/local/share/ivre/geoip/GeoIPCountryCSV.zip: done.
Unpacking: done.
ubuntu@ivre:~$ 
ubuntu@ivre: ~$ sudo ivre ipdata --import-all --no-update-passive-db
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 73, in <module>
    main()
  File "/usr/local/bin/ivre", line 51, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/ipdata.py", line 135, in main
    r[0](*r[1], **r[2])
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/mongo.py", line 3285, in feed_city_location
    for line in fdesc
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 2212, in insert
    check_keys, manipulate, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 589, in _insert
    self.__write_response_codec_options, bwc)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/message.py", line 660, in _do_batched_insert
    ctx.legacy_write(request_id, msg, 0, send_safe, to_send)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/message.py", line 543, in legacy_write
    request_id, msg, max_doc_size, acknowledged)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 290, in legacy_write
    self.send_message(msg, max_doc_size)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 261, in send_message
    self._raise_connection_failure(error)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 370, in _raise_connection_failure
    _raise_connection_failure(self.address, error)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 65, in _raise_connection_failure
    raise AutoReconnect(msg)
pymongo.errors.AutoReconnect: localhost:27017: [Errno 32] Broken pipe

**Comment by nirhenn** [comment]
Quick update, removing mongodb and pymongo and reinstalling both with pymongo 
root@ivre:~# python -m pip install --upgrade pymongo
solved the problem.
I think the pymongo version that comes with mongodb is older and cause the issue.

**Comment by p-l-** [comment]
Great, so maybe we can close this issue (and if you could update the status on #279 ;-) )?

**Comment by demokratlinux** [comment]
Please. Help.
I do not know what to do.

root@kali:~# python -m pip install --upgrade pymongo
Collecting pymongo
  Downloading https://files.pythonhosted.org/packages/e6/c1/2bc5fab47fbe48ad1238031d808854bf8726ad62835ffedaec63ba9227ea/pymongo-3.7.1-cp27-cp27mu-manylinux1_x86_64.whl (407kB)
    100% |████████████████████████████████| 409kB 272kB/s 
Installing collected packages: pymongo
  Found existing installation: pymongo 3.6.1
    Not uninstalling pymongo at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pymongo-3.7.1
root@kali:~# ivre ipdata --download
Downloading http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz to /usr/local/share/ivre/geoip/GeoLite2-Country.tar.gz: Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 84, in <module>
    main()
  File "/usr/local/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/ipdata.py", line 77, in main
    ivre.geoiputils.download_all(verbose=not args.quiet)
  File "/usr/local/lib/python2.7/dist-packages/ivre/geoiputils.py", line 152, in download_all
    udesc = opener.open(url)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden



root@kali:/usr/share/ivre# ls
geoip


root@kali:/usr/share/ivre/geoip# ls
BGP.csv  GeoIPASNum.csv     GeoIPCity-Blocks.csv  GeoIPCity-Location.csv  GeoIPCountryCSV.zip
BGP.raw  GeoIPASNumCSV.zip  GeoIPCityCSV.zip      GeoIPCountry.csv        iso3166.csv

**Comment by demokratlinux** [comment]
root@kali:~# ivre runscans --routable --limit 10
ADDING TARGET 1 : 41.239.26.241
ADDING TARGET 2 : 170.210.28.184
ADDING TARGET 3 : 81.90.175.59
ADDING TARGET 4 : 208.220.197.1
ADDING TARGET 5 : 118.32.242.69
ADDING TARGET 6 : 38.177.153.136
ADDING TARGET 7 : 164.164.6.79
ADDING TARGET 8 : 78.40.108.210
ADDING TARGET 9 : 205.64.247.152
ADDING TARGET 10 : 114.139.84.220
WROTE ALL TARGETS
NO MORE DATA TO PROCESS
root@kali:~# ivre scan2db -c ROUTABLE,ROUTABLE-CAMPAIGN-001 -s MySource -r \
> scans/ROUTABLE/up
24 results imported.
root@kali:~# 



but I do not see anything http: // localhost

button help in ivre work!!!

but no results
