### ISSUE TITLE
Maps and bar graph nota working

### ISSUE THREAD

**Issue by sanchezsantoscarlos** [cea-sec/ivre#360]
Hello, I have just installed IVRE under a Debian 8 distro following your instructions:

https://github.com/cea-sec/ivre/blob/master/doc/FAST-INSTALL-AND-FIRST-RUN.md

Imported the modbus scan results from:

http://pierre.droids-corp.org/blog/html/2015/02/24/scanning_internet_exposed_modbus_devices_for_fun___fun.html#update-2015-08-19

But we haven't been able to make maps and graph bars work.

No java or neo4j installed.

Please can you help me?

Thanks in advance.

**Comment by p-l-** [comment]
Hi,

We'll need more to investigate. Can you provide the output of the following commands:
```
python2 -c 'from ivre import config, VERSION; print config.DB; print VERSION'

ivre scancli --top port:open
```

If you're using MongoDB, please also provide the output of:
```
python2 -c 'from pymongo import version; print version'
```

**Comment by madebyacme34** [comment]
`python2 -c 'from ivre import config, VERSION; print config.DB; print VERSION'`

mongodb:///ivre
0.9.4.dev230

`python2 -c 'from pymongo import version; print version'`

2.7.2

`ivre scancli --top port:open`

Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 78, in <module>
    main()
  File "/usr/local/bin/ivre", line 51, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/scancli.py", line 498, in main
    archive=args.archives):
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/mongo.py", line 2469, in topvalues
    self.colname_hosts].aggregate(pipeline, cursor={})
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 1336, in aggregate
    "aggregate", self.__name, **command_kwargs)
  File "/usr/lib/python2.7/dist-packages/pymongo/database.py", line 351, in _command
    msg, allowable_errors)
  File "/usr/lib/python2.7/dist-packages/pymongo/helpers.py", line 178, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: command SON([('aggregate', u'hosts'), ('pipeline', [{'$match': {'ports.state_state': 'open'}}, {'$project': {'ports.protocol': 1, '_id': 0, 'ports.port': 1, 'ports.state_state': 1}}, {'$unwind': '$ports'}, {'$match': {'ports.state_state': 'open'}}, {'$project': {'ports.port': {'$concat': ['$ports.protocol', '###', {'$toLower': '$ports.port'}]}}}, {'$project': {'field': '$ports.port'}}, {'$match': {'field': {'$exists': True}}}, {'$group': {'count': {'$sum': 1}, '_id': '$field'}}, {'$sort': {'count': -1}}, {'$limit': 10}]), ('cursor', {})]) failed: unrecognized field "cursor

Thank you!

**Comment by p-l-** [comment]
Thanks. Let's continue then: what's the output of the following command: `echo 'print(db.version()); print(version());' | mongo`?

**Comment by madebyacme34** [comment]
`echo 'print(db.version()); print(version());' | mongo`

MongoDB shell version: 2.4.10
connecting to: test
2.4.10
2.4.10
bye

Thank you.
