### ISSUE TITLE
ivre fails to install with pip

### ISSUE THREAD

**Issue by tunkaflux** [cea-sec/ivre#365]
Hello,

Installing ivre with pip fails with:

```
user@box2:~/Source$ pip install ivre
Collecting ivre
  Using cached ivre-0.9.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-GWczMs/ivre/setup.py", line 71, in <module>
        version=__import__('ivre').VERSION,
      File "ivre/__init__.py", line 77, in <module>
        VERSION = _version()
      File "ivre/__init__.py", line 66, in _version
        return tag
    UnboundLocalError: local variable 'tag' referenced before assignment

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-GWczMs/ivre/
user@box2:~/Source$
```
Any idea how I can fix this? Host is Ubuntu 16.04.

**Comment by p-l-** [comment]
Hi,

Thanks for reporting this issue. Can you try again and report whether the new release fixes this?

**Comment by tunkaflux** [comment]
Yep, it works now, thanks!

**Comment by p-l-** [comment]
Thanks, happy scanning!
