### ISSUE TITLE
ivre scan2db problem when re-scan a host

### ISSUE THREAD

**Issue by fjavierc** [cea-sec/ivre#367]
I recently updated to the latest version (0.9.5) but now, when I scan again a host and i'm going to import with "ivre scan2db" I get the following errors.

I have tried with version 0.9.4 and I also have the same problem. I do not know if it can be something of my team or not.

To reproduce this error:

1. Scaning a host, runnig 'ivre runscans'
> User@host Directory1 # ivre runscans --categories PRUEBAS --range 1.2.3.4 1.2.3.4

2. Running "Ivre scan2db"

> User@host Directory1 # ivre scan2db -c PRUEBAS -s localhost -r scans
2 results imported.

Now, days later or by stopping / starting services in 1.2.3.4:

3. Scan again the host 1.2.3.4
> User @ host Directory2 # ivre runscans --categories PRUEBAS --range 1.2.3.4 1.2.3.4

4. Import results to ivre; "Ivre scan2db ..."
> User @ host Directory2 # ivre scan2db -c PRUEBAS -s localhost -r scans /
2 results found.
WARNING: ivre: Exception (file 'scans/PRUEBAS/up/1/2/3/4.xml')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/scan2db.py", line 119, in main
    Merge = args.merge, masscan_probes = args.masscan_probes,
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 353, in store_scan
    Return store_scan_function (fname, filehash = scanid, ** kargs)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 374, in store_scan_xml
    Parser.parse (utils.open_file (fname))
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    Xmlreader.IncrementalParser.parse (self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    Self.feed (buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    Self._parser.Parse (data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 307, in end_element
    Self._cont_handler.endElement (name)
  File "/usr/local/lib/python2.7/dist-packages/ivre/xmlnmap.py", line 1220, in endElement
    Self._addhost ()
  File "/usr/local/lib/python2.7/dist-packages/ivre/xmlnmap.py", line 1490, in _addhost
    Merge = self.merge)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/mongo.py", line 1150, in store_or_merge_host
    Self.archive_from_func (host, gettoarchive)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/mongo.py", line 1209, in archive_from_func
    Self.archive (rec)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/mongo.py", line 1201, in archive
    Utils.logger.DEBUG (
AttributeError: 'module' object has no attribute 'logger'
1 Displaying 1 - 1 of 1 imported.

And now, the host with ip 1.2.3.4, disappears from Ivre ( ?¿??¿ ) and I need to scan again:

Runscans ...
> User @ host Directory3 # ivre runscans --categories PRUEBAS --range 1.2.3.4 1.2.3.4
ADDING TARGET 1 : 1.2.3.4
WROTE ALL TARGETS
NO MORE DATA TO PROCSESS

Scan2db ...
>User @ host Directory3 # ivre scan2db -c PRUEBAS -s localhost -r scans/
2 results imported.

Some clue ?? Thanks !!

**Comment by p-l-** [comment]
Thanks for reporting this bug. The patch in #368 should fix it. Can you confirm that it works for you?

Thanks again!

**Comment by fjavierc** [comment]
Hi Pierre !!

I solved the problem with your fix ! ( #368 ). 

Thank you very much P-L, you are the best !!

:-)
