### ISSUE TITLE
runscansagentdb does not work with --file switch

### ISSUE THREAD

**Issue by Golbark** [cea-sec/ivre#396]
### IVRE Version

```
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.5.dev2

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.4.0
    Python module py2neo: 3.1.2
    Python module sqlalchemy: 1.1.8
    Python module psycopg2: 2.7.1 (dt dec pq3 ext lo64)
```

### Summary

ivre runscansagentdb crashes if the --file flag is used. This apparently comes from the fact that the file object is put in memory and pickle cannot dump it

### Expected behavior

Ivre should not crash as the --file switch can be used according to the documentation

### Actual behavior

```
$ ivre runscansagentdb --file /path/to/my/file
Traceback (most recent call last):
  File "/bin/ivre", line 78, in <module>
    main()
  File "/bin/ivre", line 51, in main
    tools.get_command(possible_commands[0])()
  File "/usr/lib/python2.7/site-packages/ivre/tools/runscansagentdb.py", line 192, in main
    assign_to_free_agents=bool(args.assign_free_agents)
  File "/usr/lib/python2.7/site-packages/ivre/db/__init__.py", line 1450, in add_scan
    "target": pickle.dumps(target.__iter__()),
  File "/usr/lib64/python2.7/pickle.py", line 1374, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib64/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib64/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib64/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/lib64/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib64/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib64/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/usr/lib64/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "/usr/lib64/python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: can't pickle file objects
```

### How to reproduce

See command above

**Comment by p-l-** [comment]
Hi @Golbark!

Sorry it took so long, I wanted to add tests to prevent further regressions and found a **lot** of other bugs :).

Thanks for your report, please let us know if there is still something wrong (or if it works for you, that's always nice!). If you are using Docker, the images should be ready really soon.
