### ISSUE TITLE
scansagentsdb issue

### ISSUE THREAD

**Issue by njzy** [cea-sec/ivre#400]
### IVRE Version
```
root@1a9c3fc6e476:/# ivre version
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.6.dev5

Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118]

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.4.0
    Python module py2neo: 3
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: missing
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
```

### Summary

ivre runscansagentdb --list-scans issue
ivre runscansagentdb --daemon issue

### Actual behavior
**ivre runscansagentdb --list-scans**
```
root@1a9c3fc6e476:/# ivre runscansagentdb --list-scans
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 78, in <module>
    main()
  File "/usr/local/bin/ivre", line 51, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscansagentdb.py", line 210, in main
    display_scan(scan)
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscansagentdb.py", line 39, in display_scan
    scan['target'] = ivre.db.db.agent.get_scan_target(scan['_id'])
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1461, in get_scan_target
    return pickle.loads(self._get_scan_target(self, scanid))
TypeError: _get_scan_target() takes exactly 2 arguments (3 given)
```
**ivre runscansagentdb --daemon**
```
root@1a9c3fc6e476:/# ivre runscansagentdb --daemon
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 78, in <module>
    main()
  File "/usr/local/bin/ivre", line 51, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscansagentdb.py", line 231, in main
    ivre.db.db.agent.feed_all(masterid)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1354, in feed_all
    self.feed(masterid, scanid)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1357, in feed
    scan = self.lock_scan(scanid)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1468, in lock_scan
    scan = self._lock_scan(scanid, None, lockid.bytes)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/mongo.py", line 3369, in _lock_scan
    if "target_info" not in scan:
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by p-l-** [comment]
As stated in [CONTRIBUTING](/cea-sec/ivre/blob/master/.github/CONTRIBUTING.md#bugs), please try again with the latest development version.
I'm closing this issue because I feel like this has been fixed in #397, please reopen it if that's not the case.
