### ISSUE TITLE
runscansagentdb does not work with --daemon 

### ISSUE THREAD

**Issue by njzy** [cea-sec/ivre#403]
### IVRE Version
```
root@ivreclient:~#  ivre version
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.6.dev28

Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118]

Linux ivreclient 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.4.0
    Python module py2neo: 3
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: missing
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
```

### Summary

runscansagentdb does not work with --daemon 

### Actual behavior
```
root@ivreclient:~# ivre runscansagentdb --daemon  
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 78, in <module>
    main()
  File "/usr/local/bin/ivre", line 51, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscansagentdb.py", line 231, in main
    ivre.db.db.agent.feed_all(masterid)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1351, in feed_all
    self.feed(masterid, scanid)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1354, in feed
    scan = self.lock_scan(scanid)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1486, in lock_scan
    scan = self._lock_scan(scanid, None, lockid.bytes)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/mongo.py", line 3372, in _lock_scan
    if "target_info" not in scan:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by p-l-** [comment]
Are you running another daemon when you get this error? Or did another daemon crash before? This could happen when, for some reason, the daemon cannot acquire the lock for the scan. Anyway you should get a nice error message rather than a crash!

**Comment by p-l-** [comment]
Can you apply the patch from #404 and report the output of `ivre runscansagentdb --list-scans`?

**Comment by Golbark** [comment]
I also got this error at some point after a system crash. The way I solved it was to connect manually to the MongoDB and empty the lock value on the scan object. @p-l- that would be nice to have some kind of --force or --cleanup switch that would remove all locks to recover after crash.

**Comment by p-l-** [comment]
Can you apply the (new) patch from #404 and report here if `ivre runscansagentdb --force-unlock` works for you?
