### ISSUE TITLE
nmap2db: 'dict' object has no attribute 'append'

### ISSUE THREAD

**Issue by r00t0vi4** [cea-sec/ivre#406]
### IVRE Version
```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.6

Python 2.7.13 (default, Jan 19 2017, 14:48:08)
[GCC 6.3.0 20170118]

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.4.0
    Python module py2neo: 3.1.2
    Python module sqlalchemy: 1.1.13
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: 4.0.0
    Python module MySQLdb: missing
    Python module dbus: 1.2.4
    Python module matplotlib: 2.0.2

```

### Summary
Error while importing nmap results.
Scan command:
```
ivre runscans -n 10.10.10.10/32 --output=XMLFork --nmap-template default
```
Import command
```
 ivre nmap2db -c cat -s scanner -r ./scans/ --never-archive
```

Results:
```
WARNING:ivre:Exception (file './scans/NET-10.10.10.10_32/up/10/10/10/10.xml')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/scan2db.py", line 122, in main
    merge=args.merge, masscan_probes=args.masscan_probes,
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 362, in store_scan
    return store_scan_function(fname, filehash=scanid, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 383, in store_scan_xml
    parser.parse(utils.open_file(fname))
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 317, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/usr/local/lib/python2.7/dist-packages/ivre/xmlnmap.py", line 1158, in startElement
    lastlevel.append(obj)
AttributeError: 'dict' object has no attribute 'append'
0 results imported.
```

The problem was solved after deleting this strings from xml report:
```
<script id="fcrdns" output="FAIL (No PTR record)"><table key="&lt;none&gt;">
<elem key="status">fail</elem>
<elem key="reason">No PTR record</elem>
</table>
</script>
```

**Comment by p-l-** [comment]
Hi,

Thanks for reporting it. Could you share the exact scan result (or a similar one that will cause the same crash), either here or in private via e-mail (`dev (a) ivre.rocks`), so that I can reproduce the bug and figure out the best option to fix it?

Thanks again!

**Comment by p-l-** [comment]
@r00t0vi4 Thanks for sharing the sample, that was very useful!
I've submitted a patch (#409 - tests are running). Can you try it out and report it works for you? It works on the sample you've sent.

**Comment by r00t0vi4** [comment]
Thanks a lot. Import successfully finished.

**Comment by p-l-** [comment]
Thanks!
