### ISSUE TITLE
UnicodeDecodeError using IVRE nmap2db (for BANNER)

### ISSUE THREAD

**Issue by mariudelros** [cea-sec/ivre#418]
Hello,
during the step of import a masscan result using nmap2db, 

sudo ivre nmap2db --archive --c MASSCAN-BANNER -s SCANNER BANNER.xml 

I usually have this kind of error:

**UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
0 results imported.**

Could you please tell me how may I solve this?

Error tree:

```
user@workstation:~/masscan/bin$ ivre nmap2db --archive --c MASSCAN-BANNER -s SCANNER BANNER.xml 
WARNING:ivre:Exception (file 'BANNER.xml')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/scan2db.py", line 122, in main
    merge=args.merge, masscan_probes=args.masscan_probes,
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 362, in store_scan
    return store_scan_function(fname, filehash=scanid, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 383, in store_scan_xml
    parser.parse(utils.open_file(fname))
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 304, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/usr/local/lib/python2.7/dist-packages/ivre/xmlnmap.py", line 1109, in startElement
    probe=probe,
  File "/usr/local/lib/python2.7/dist-packages/ivre/utils.py", line 843, in get_nmap_svc_fp
    _read_nmap_probes()
  File "/usr/local/lib/python2.7/dist-packages/ivre/utils.py", line 832, in _read_nmap_probes
    parse_line(line[:-1])
  File "/usr/local/lib/python2.7/dist-packages/ivre/utils.py", line 825, in parse_line
    value = value.decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
0 results imported.
```
Thank you!
M.

IVRE VERSION:

IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.6.dev48

Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]

14.04.1-Ubuntu SMP Mon Aug 14 16:07:05 UTC 2017 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 2.7.2
    Python module py2neo: 3.1.2
    Python module sqlalchemy: 1.0.12
    Python module psycopg2: 2.7.3.1 (dt dec pq3 ext lo64)
    Python module krbV: missing
    Python module PIL: [unknown version]
    Python module MySQLdb: 1.2.3
    Python module dbus: 1.2.0
    Python module matplotlib: 1.3.1

**Comment by p-l-** [comment]
Thanks for this report. Please e-mail a sample to `dev` [at] `ivre` [dot] `rocks`.

**Comment by mariudelros** [comment]
Thanks a lot. E-mail sent.

**Comment by p-l-** [comment]
@mariudelros thanks for the report and thanks for the sample!
