### ISSUE TITLE
Inappropriate ioctl for device

### ISSUE THREAD

**Issue by r00t0vi4** [cea-sec/ivre#424]
### IVRE Version
```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.6

Python 2.7.13 (default, Jan 19 2017, 14:48:08)
[GCC 6.3.0 20170118]

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.4.0
    Python module py2neo: 3.1.2
    Python module sqlalchemy: 1.1.13
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: 4.0.0
    Python module MySQLdb: missing
    Python module dbus: 1.2.4
    Python module matplotlib: 2.0.2

```

### Summary
Error while executing runscans command from cron script
Results:
```
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 78, in <module>
    main()
  File "/usr/local/bin/ivre", line 51, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscans.py", line 434, in main
    restore_echo()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscans.py", line 187, in restore_echo
    attrs = termios.tcgetattr(fdesc)
termios.error: (25, 'Inappropriate ioctl for device')
```

The problem was solved by adding try/except to runscans.py:
```
    try:
        fdesc = sys.stdin.fileno()
        attrs = termios.tcgetattr(fdesc)
        attrs[3] = attrs[3] | termios.ECHO
        termios.tcsetattr(fdesc, termios.TCSADRAIN, attrs)
    except:
        pass
```

**Comment by p-l-** [comment]
Hi, I totally forgot to close your issue, sorry. This bug has been fixed in commit 49ba291067542cf1693f9ecc7b25557815ed7676, merged in #401. Thanks a lot for reporting it!
