### ISSUE TITLE
ipdata --update-indexes results in  mongo deduplication error 

### ISSUE THREAD

**Issue by royharoush** [cea-sec/ivre#425]
### IVRE Version
```
root@ivreclient:/# ivre version
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.6.dev70

Python 2.7.13 (default, Jan 19 2017, 14:48:08)
[GCC 6.3.0 20170118]

Linux ivreclient 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.4.0
    Python module py2neo: 3
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: missing
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing

root@ivreclient:/#

```

### Summary

deduplication is failing on mongo when trying to run "ipdata --ensure-indexes" 

### Expected behavior
indexes to be created in mongo and IP addresses to have AS and location updated for them. 

### Actual behavior

```
ivre ipdata: error: unrecognized arguments: --ensure-indexs
root@ivreclient:/# ivre ipdata --ensure-indexe
This will lock your database. Process ? [y/N] y
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 78, in <module>
    main()
  File "/usr/local/bin/ivre", line 51, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/ipdata.py", line 105, in main
    ivre.db.db.data.ensure_indexes()
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/mongo.py", line 204, in ensure_indexes
    self.db[colname].ensure_index(index[0], **index[1])
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 1562, in ensure_index
    self.__create_index(keys, kwargs)
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 1430, in __create_index
    parse_write_concern_error=True)
  File "/usr/lib/python2.7/dist-packages/pymongo/collection.py", line 232, in _command
    collation=collation)
  File "/usr/lib/python2.7/dist-packages/pymongo/pool.py", line 419, in command
    collation=collation)
  File "/usr/lib/python2.7/dist-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/lib/python2.7/dist-packages/pymongo/helpers.py", line 203, in _check_command_response
    raise DuplicateKeyError(errmsg, code, response)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: ivre.countries index: country_code_1 dup key: { : "A1" }
root@ivreclient:/#

```

### How to reproduce

 ivre ipdata --ensure-indexe
### More
i'm running this on dockers on a system with 2gb of ram, but as far as i can see this isn't a resource problem. 
I've added multiple scans that i ran from different locations (using nmap). the scans have different port-ip matching (a sample scan is "nmap target -p 80", and the other would be "nmap target -p 443")

Thanks,
Roy

**Comment by p-l-** [comment]
I don't know how you got there! Let's try to understand that. Did you run `ivre ipdata --init` during the installation / initial setup?

**Comment by royharoush** [comment]
i did, but then i populated alot of scan data into my database, and it wasnt showing the AS numbers geolocation so i ran ipdata --update-indexes  assuming it will run across the database and assign this attributes to each IP. was my assumption wrong ?

**Comment by p-l-** [comment]
Yes, your assumption was wrong. What gives `ivre ipdata 8.8.8.8`?

**Comment by p-l-** [comment]
No answer, cannot reproduce. Please reopen if needed.
