### ISSUE TITLE
airodump2db error

### ISSUE THREAD

**Issue by marcotuna** [cea-sec/ivre#434]
```
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.6.dev74

Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]

Linux Ivre 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.5.1
    Python module py2neo: 3.1.2
    Python module sqlalchemy: 1.1.15
    Python module psycopg2: 2.7.3.2 (dt dec pq3 ext lo64)
    Python module krbV: [unknown version]
    Python module PIL: [unknown version]
    Python module MySQLdb: 1.3.7
    Python module dbus: 1.2.0
    Python module matplotlib: 1.5.1
```

Command: 

`root@Ivre:/opt# ivre airodump2db WifiCap19112017-01.csv`

Output:

```
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 78, in <module>
    main()
  File "/usr/local/bin/ivre", line 51, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/airodump2db.py", line 54, in main
    for line in fdesc:
  File "/usr/local/lib/python2.7/dist-packages/future/types/newobject.py", line 71, in next
    return type(self).__next__(self)
  File "/usr/local/lib/python2.7/dist-packages/ivre/parser/airodump.py", line 64, in __next__
    line = next(super(Airodump, self)).rstrip('\r\n')
TypeError: super object is not an iterator
```
[WifiCap19112017-01.txt](https://github.com/cea-sec/ivre/files/1486059/WifiCap19112017-01.txt)

**Comment by p-l-** [comment]
Hi,

Thanks for this report, sorry it took so long to handle it. #444 should fix this bug. Can you confirm that?
