### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED on ivre ipdata

### ISSUE THREAD

**Issue by jakevis** [cea-sec/ivre#475]
### IVRE Version

root@ivreclient:/# ivre version
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.7.dev4

Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516]

Linux ivreclient 4.9.75-linuxkit-aufs #1 SMP Tue Jan 9 10:58:17 UTC 2018 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.4.0
    Python module py2neo: 3
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: 4.0.0
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing

### Summary

When running ivre ipdata --download --import-all --no-update-passive-db I get this failure:

Downloading http://dev.maxmind.com/static/csv/codes/iso3166.csv to /usr/local/share/ivre/geoip/iso3166.csv: Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 78, in <module>
    main()
  File "/usr/local/bin/ivre", line 51, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/ipdata.py", line 107, in main
    ivre.geoiputils.download_all(verbose=not args.quiet)
  File "/usr/local/lib/python2.7/dist-packages/ivre/geoiputils.py", line 125, in download_all
    udesc = opener.open(url)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>

**Comment by jakevis** [comment]
This is using a newly created Docker instance

**Comment by p-l-** [comment]
Thanks a lot for reporting this. This should be fixed by #476, new Docker images are being built and should be ready really soon.

**Comment by p-l-** [comment]
New images are now built and ready. Just pull them again, and run (tested, works fine for me). Please reopen if needed.
