### ISSUE TITLE
possible files missing from Docker container

### ISSUE THREAD

**Issue by joefizz** [cea-sec/ivre#551]
Please try to follow this template. Also, please format your issue
properly (particularly to report code or command line output). You may
want to read
[Github's basic writing and formatting syntax](https://help.github.com/articles/basic-writing-and-formatting-syntax/).

### IVRE Version

Insert here the output of the command `ivre version`, displayed as
code. For example:

```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.10.dev105

Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516]

Linux 2dedd34486be 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.4.0
    Python module py2neo: 3
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: 4.0.0
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.13

```

### Summary

I've just fired up the docker container using vagrant as explained in the docs however when trying the first example an error is thrown indicating missing files.  Tried to find the files online manually but not successful.
 
### Expected behavior

Running the command `ivre runscans --routable --limit 1000 --output=XMLFork` should start scans.

### Actual behavior

```root@2dedd34486be:/tmp# ivre runscans --routable --limit 1000 --output=XMLFork
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 84, in <module>
    main()
  File "/usr/local/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscans.py", line 417, in main
    targets = ivre.target.target_from_args(args)
  File "/usr/local/lib/python2.7/dist-packages/ivre/target.py", line 476, in target_from_args
    state=args.state)
  File "/usr/local/lib/python2.7/dist-packages/ivre/target.py", line 215, in __init__
    geoiputils.get_routable_ranges(),
  File "/usr/local/lib/python2.7/dist-packages/ivre/geoiputils.py", line 274, in <lambda>
    get_routable_ranges = lambda: get_ranges_by_data('BGP.csv', lambda _: True)
  File "/usr/local/lib/python2.7/dist-packages/ivre/geoiputils.py", line 243, in get_ranges_by_data
    for start, stop in _get_by_data(datafile, condition):
  File "/usr/local/lib/python2.7/dist-packages/ivre/geoiputils.py", line 234, in _get_by_data
    fdesc = open(os.path.join(config.GEOIP_PATH, datafile))
IOError: [Errno 2] No such file or directory: '/usr/local/share/ivre/geoip/BGP.csv'```

### How to reproduce

run the above command from the docker container

### More

**Comment by Maximevilla** [comment]
did u do the init staff ?

2018-07-13 23:52 GMT+02:00 joefizz <notifications@github.com>:

**Comment by joefizz** [comment]
Do I need to?  is that this stuff?

```$ ivre scancli --init
This will remove any scan result in your database. Process ? [y/N] y
$ ivre ipinfo --init
This will remove any passive information in your database. Process ? [y/N] y
$ sudo ivre runscansagentdb --init
This will remove any agent and/or scan in your database and files. Process ? [y/N] y
$ sudo ivre ipdata --download
$ ivre ipdata --import-all
```

**Comment by p-l-** [comment]
Yep, you have to run this.
