### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by elouet** [cea-sec/ivre#571]
### IVRE Version

Insert here the output of the command `ivre version`, displayed as
code. For example:

```
$ ivre version
VRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.11

Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516]

Linux oshima-vbox 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.7.1
    Python module py2neo: 4.1.0
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: 4.0.0
    Python module MySQLdb: missing
    Python module dbus: 1.2.4
    Python module matplotlib: missing
    Python module bottle: 0.12.13

```

### Summary

Unable to run ivre flowcli --init

### Expected behavior

ivre supposedly sets up database.

### Actual behavior

```
This will remove any scan result in your database. Process ? [y/N] y
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 84, in <module>
    main()
  File "/usr/local/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/home/lou/.local/lib/python2.7/site-packages/ivre/tools/flowcli.py", line 114, in main
    db.flow.init()
AttributeError: 'MetaDB' object has no attribute 'flow'
```

### How to reproduce

Install as per step-by-step instruction from git repo or using pip, either way same result.

### More

Please include any other information that could help us. We will be
able to help you faster if we don't have to ask questions and wait for
your answers.

**Comment by p-l-** [comment]
Hi,

Thanks for this report.

Could you report the output of the following command: `python -c "import ivre.config; print(ivre.config.DB_FLOW)"`?

**Comment by p-l-** [comment]
Closing for no activity. Please reopen this issue if you still need help.

**Comment by p-l-** [comment]
@bib0x Thanks for this report. I'm not sure whether this is the same issue, but I'm going to reopen it so we can track your problem.

Could you report the output of `ivre version`?
