### ISSUE TITLE
runscansagentdb custom scan

### ISSUE THREAD

**Issue by AnthoDingo** [cea-sec/ivre#576]
### IVRE Version

```
# ivre version
IVRE - Network recon framework
Copyright 2011 - 2017 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.11.dev25

Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516]

Linux 7df8b1cc28b6 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.4.0
    Python module py2neo: 3
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: 4.0.0
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.13
```

### Summary

Can't create scan

### Expected behavior

Create an assign a scan task to free agents

### Actual behavior

```
# ivre runscansagentdb --assign-free-agents -c FR --nmap-prescan-ports 22 80 443 --limit 10
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 84, in <module>
    main()
  File "/usr/local/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscansagentdb.py", line 211, in main
    assign_to_free_agents=bool(args.assign_free_agents)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1653, in add_scan
    itertarget.fdesc = (True, fdesc.tell())
IOError: [Errno 29] Illegal seek
```

### How to reproduce

In docker ivre/agent:latest container, after init all db, after adding agent

```
# ivre runscansagentdb --list-agents                                                       
agent:
  - id: 5bb6a4b974285806339c6999
  - source name: MySource
  - remote host: agentweb
  - remote path: /var/lib/ivre-agent/
  - master: 5bb6a4b27428580629923486
  - local path: /var/lib/ivre/master/kvKFh5
  - rsync command: rsync
  - current scan: None
  - currently synced: True
  - max waiting targets: 60
  - waiting targets: 0
  - current targets: 0
  - can receive: 60
```

I can't start a custom scan. I test the example scan, and it work fine.
```
$ ivre runscansagentdb --assign-free-agents --routable --limit 1000
```

**Comment by p-l-** [comment]
I do not understand your issue. Can you explain what you want to do? If you can run the example scan, what kind of scan would you like to run?

**Comment by AnthoDingo** [comment]
I can't run any other scan than the example. Every scan return the same error :
```
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 84, in <module>
    main()
  File "/usr/local/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscansagentdb.py", line 211, in main
    assign_to_free_agents=bool(args.assign_free_agents)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1653, in add_scan
    itertarget.fdesc = (True, fdesc.tell())
IOError: [Errno 29] Illegal seek
```

**Comment by p-l-** [comment]
I think the `--nmap-prescan-ports` must be used when you create the agent, not when you run the scan itself, since the Nmap options are hardcoded in the agent. Can you try without it? Something like:

    ivre runscansagentdb --assign-free-agents --country FR

**Comment by p-l-** [comment]
Exactly! Can we close this issue?
