### ISSUE TITLE
Top values broken for JSON fields with SQLite backend

### ISSUE THREAD

**Issue by p-l-** [cea-sec/ivre#642]
Please try to follow this template. Also, please format your issue
properly (particularly to report code or command line output). You may
want to read
[Github's basic writing and formatting syntax](https://help.github.com/articles/basic-writing-and-formatting-syntax/).

### IVRE Version

Current development version (`0.9.11.dev_master_211`).

### Summary

`.topvalues()` is broken for JSON subfields with SQLite backend.

### Expected behavior

```
$ ivre ipinfo --top infos.service_product --service ftp
Pure-FTPd: 1
```

### Actual behavior

```
$ ivre ipinfo --top infos.service_product --service ftp
Traceback (most recent call last):
  File "/usr/bin/ivre", line 84, in <module>
    main()
  File "/usr/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/usr/lib/python3.7/site-packages/ivre/tools/ipinfo.py", line 338, in main
    args.skip or 0)
  File "/usr/lib/python3.7/site-packages/ivre/tools/ipinfo.py", line 163, in <lambda>
    limit)
  File "/usr/lib/python3.7/site-packages/ivre/utils.py", line 1558, in display_top
    for entry in db.topvalues(field, flt=flt, topnbr=lmt or 10, least=least):
  File "/usr/lib/python3.7/site-packages/ivre/db/sql/__init__.py", line 1901, in <genexpr>
    for result in self.db.execute(req.order_by(order).limit(topnbr))
  File "/usr/lib/python3.7/site-packages/ivre/db/sql/tables.py", line 138, in process
    value = json.loads(value)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### How to reproduce

Use an SQLite database, insert the results used for the Travis CI tests and run `ivre ipinfo --top infos.service_product --service ftp`.

### More

When this bug is fixed, a new test can be added (the output of `ivre ipinfo --top infos.service_product --service ftp` for example).

The following code block in the test should also be removed:
https://github.com/cea-sec/ivre/blob/3ca7ff1724a71f0f3b07afe3f7840b03d71c1188/tests/tests.py#L1532-L1535

**Comment by Nutigoodpipes** [comment]
Added special cases to fix : 
https://github.com/cea-sec/ivre/blob/6d15a8519086b98adc567fc0a69a51887e74e588/tests/tests.py#L2054-L2056
https://github.com/cea-sec/ivre/blob/6d15a8519086b98adc567fc0a69a51887e74e588/ivre/db/sql/__init__.py#L1932-L1937

**Comment by Nutigoodpipes** [comment]
May be this is better to get rid of all this stuff and use the JSON sqlite native type thus require SQLite version 3.9.0 minimum.

https://github.com/cea-sec/ivre/blob/6d15a8519086b98adc567fc0a69a51887e74e588/ivre/db/sql/tables.py#L77-L81
The "$." here, is actually sqlite JSON "well-formed" path according to the [doc](https://www.sqlite.org/json1.html)

Note : This would also require sqlalchemy >= 1.3.0 for sqlite backend
