### ISSUE TITLE
AttributeError: 'Neo4jDBFlow' object has no attribute '_db'

### ISSUE THREAD

**Issue by secnum** [cea-sec/ivre#729]
### IVRE Version

```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2019 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.13.dev35

Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

Linux ivre 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.8.0
    Python module py2neo: 3.1.2
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: missing
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.17
```

### Summary

Another Python error after ivre flowcli --init.

### Expected behavior

No Python traceback should occurs.

### Actual behavior

This will remove any flow result in your database. Process ? [y/N] y
Traceback (most recent call last):
  File "/home/test/envivre/lib/python3.6/site-packages/ivre/db/neo4j.py", line 71, in db
    return self._db
AttributeError: 'Neo4jDBFlow' object has no attribute '_db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/test/envivre/lib/python3.6/site-packages/py2neo/database/__init__.py", line 318, in __new__
    inst = cls.__instances[key]
KeyError: (<class 'py2neo.database.Graph'>, <ServerAddress settings={'host': 'localhost', 'http_port': 7474}>, 'data')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/test/envivre/lib/python3.6/site-packages/py2neo/database/http.py", line 154, in get
    response = self.__base.get(headers=headers, redirect_limit=redirect_limit, **kwargs)
  File "/home/test/envivre/lib/python3.6/site-packages/py2neo/packages/httpstream/http.py", line 966, in get
    return self.__get_or_head("GET", if_modified_since, headers, redirect_limit, **kwargs)
  File "/home/test/envivre/lib/python3.6/site-packages/py2neo/packages/httpstream/http.py", line 943, in __get_or_head
    return rq.submit(redirect_limit=redirect_limit, **kwargs)
  File "/home/test/envivre/lib/python3.6/site-packages/py2neo/packages/httpstream/http.py", line 452, in submit
    return Response.wrap(http, uri, self, rs, **response_kwargs)
  File "/home/test/envivre/lib/python3.6/site-packages/py2neo/packages/httpstream/http.py", line 489, in wrap
    raise inst
py2neo.packages.httpstream.http.ClientError: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/test/envivre/bin/ivre", line 84, in <module>
    main()
  File "/home/test/envivre/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/home/test/envivre/lib/python3.6/site-packages/ivre/tools/flowcli.py", line 106, in main
    db.flow.init()
  File "/home/test/envivre/lib/python3.6/site-packages/ivre/db/neo4j.py", line 99, in init
    self.drop()
  File "/home/test/envivre/lib/python3.6/site-packages/ivre/db/neo4j.py", line 88, in drop
    self.db.run(query)
  File "/home/test/envivre/lib/python3.6/site-packages/ivre/db/neo4j.py", line 73, in db
    self._db = Graph(self.dburl)
  File "/home/test/envivre/lib/python3.6/site-packages/py2neo/database/__init__.py", line 327, in __new__
    use_bolt = version_tuple(inst.__remote__.get().content["neo4j_version"]) >= (3,)
  File "/home/test/envivre/lib/python3.6/site-packages/py2neo/database/http.py", line 163, in get
    raise_from(GraphError(message, **content), error)
  File "/home/test/envivre/lib/python3.6/site-packages/py2neo/util.py", line 122, in raise_from
    raise exception
py2neo.database.status.GraphError: HTTP GET returned response 403

### How to reproduce

Launch ivre flowcli --init.

### More

Neo4jDB untouched.

**Comment by p-l-** [comment]
It seems that you have an authentication error when connecting to the Neo4j database (from your error message: `py2neo.packages.httpstream.http.ClientError: 403 Forbidden`.

The default attempts to connect with `neo4j` as username and password to the database on `localhost`. You can create a config file (or edit your existing config file) `/etc/ivre.conf` and add a line like:
```
DB_FLOW = "neo4j://username:password@localhost:7474/"
```
or:
```
DB_FLOW = "neo4j://username:password@remote_host:7474/"
```

Can you please let us know if this works?

**Comment by secnum** [comment]
This doesn't work. Furthermore in `config.py`, `DB_FLOW` is well set. In addition, I reset neo4j DB passwords with `sudo neo4j-admin set-initial-password neo4j` and `sudo neo4j-admin set-default-admin neo4j`.

**Comment by p-l-** [comment]
You should never change `config.py`, as stated [in the documentation](https://doc.ivre.rocks/en/latest/install/installation.html#configuration). It only contains the default values. Create a config file to enter your specific values.

Can you connect with a web browser to `http://localhost:7474/` and authenticate?

**Comment by secnum** [comment]
I didn't change anything in `config.py`. It was only a values checking. I uncommented `dbms.connectors.default_listen_address=0.0.0.0 ` and now `ivre flowcli --init` works. That's strange because IVRE and its dependencies are on a single virtual machine.

**Comment by p-l-** [comment]
All right, thanks for letting us know.
