### ISSUE TITLE
ivre passiverecon2db fails

### ISSUE THREAD

**Issue by secnum** [cea-sec/ivre#732]
### IVRE Version

```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2019 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.13.dev37

Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

Linux ivre 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.8.0
    Python module py2neo: 3.1.2
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: missing
    Python module MySQLdb: missing
    Python module dbus: 1.2.6
    Python module matplotlib: missing
    Python module bottle: 0.12.17

```

### Summary

ivre passiverecon2db fails to import bro data into db.

### Expected behavior

No error

### Actual behavior

Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 84, in <module>
    main()
  File "/usr/local/bin/ivre", line 56, in main
    tools.get_command(possible_commands[0])()
  File "/usr/local/lib/python3.6/dist-packages/ivre/tools/passiverecon2db.py", line 95, in main
    getinfos=ivre.passive.getinfos
  File "/usr/local/lib/python3.6/dist-packages/ivre/db/mongo.py", line 3867, in insert_or_update_bulk
    for firstseen, lastseen, spec in generator(specs):
  File "/usr/local/lib/python3.6/dist-packages/ivre/db/mongo.py", line 3858, in generator
    for timestamp, spec in specs:
  File "/usr/local/lib/python3.6/dist-packages/ivre/tools/passiverecon2db.py", line 53, in rec_iter
    line["timestamp"] = line.pop("ts")
KeyError: 'ts

### How to reproduce

```
mkdir logs
sudo LOG_PATH=logs/passiverecon bro -b /usr/local/share/ivre/bro/ivre/passiverecon/bare.bro -C -i enp0s3
ivre passivereconworker --directory=logs
ivre passiverecon2db
```

**Comment by secnum** [comment]
Sorry didn't see that passivereconworker acts as passiverecon2db.
