### ISSUE TITLE
Errors with "--zmap-prescan-port"

### ISSUE THREAD

**Issue by flavioveloso3** [cea-sec/ivre#795]
### IVRE Version

```
IVRE - Network recon framework
Copyright 2011 - 2019 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.14.dev4

Python 3.6.8 (default, Aug 20 2019, 17:12:48)
[GCC 8.3.0]

Linux sosibibu 5.0.0-1018-azure #19~18.04.1-Ubuntu SMP Wed Aug 21 05:13:05 UTC 2019 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.6.1
    Python module py2neo: missing
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: missing
    Python module MySQLdb: missing
    Python module dbus: 1.2.6
    Python module matplotlib: missing
    Python module bottle: 0.12.13
```

### Summary

Found several problems with "--zmap-prescan-port" option enabled.

### Expected behavior
On Ubuntu 18.04 with Python 3.6.8 when trying to start scan with port prescan `ivre runscans --country FR --zmap-prescan-port 80 --output XMLFork`
got error:

```
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 84, in <module>
    main()
  File "/usr/local/bin/ivre", line 56, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.6/dist-packages/ivre/tools/runscans.py", line 420, in main
    targets = ivre.target.target_from_args(args)
  File "/usr/local/lib/python3.6/dist-packages/ivre/target.py", line 502, in target_from_args
    zmap_opts=zmap_prescan_opts,
  File "/usr/local/lib/python3.6/dist-packages/ivre/target.py", line 360, in __init__
    self.tmpfile.write("%s\n" % net)
  File "/usr/lib/python3.6/tempfile.py", line 624, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
```
But when trying to do same operation on Ubuntu 18.04 with Python 2.7.15+ command working well:

```
root@revest:/home/ivruser# ivre runscans --country FR --zmap-prescan-port 80 --output XMLFork
Sep 30 14:18:31.615 [INFO] zmap: output module: csv
 0:00 0%; send: 184 0 p/s (2.84 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:01 0%; send: 25629 25.4 Kp/s (24.1 Kp/s avg); recv: 52 51 p/s (48 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.20%
```
Second error(but not sure if it should be so) appears when trying to use --zmap-prescan-port with --file option (  `ivre runscans --file file.txt --zmap-prescan-port 80 --output XMLFork` )
I've trying to generate file.txt like this:
`ivre runscans --country FR --output ListAll` or `ivre runscans --country FR --output List` or `ivre runscans --country FR --output ListCIDRs` and always getting this error when trying to scan with command `ivre runscans --file file.txt --zmap-prescan-port 80 --output XMLFork` 

```
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 84, in <module>
    main()
  File "/usr/local/bin/ivre", line 56, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/runscans.py", line 420, in main
    targets = ivre.target.target_from_args(args)
  File "/usr/local/lib/python2.7/dist-packages/ivre/target.py", line 502, in target_from_args
    zmap_opts=zmap_prescan_opts,
  File "/usr/local/lib/python2.7/dist-packages/ivre/target.py", line 358, in __init__
    for start, count in viewvalues(target.targets.ranges):
AttributeError: 'TargetFile' object has no attribute 'targets'
```

System info:

```
IVRE - Network recon framework
Copyright 2011 - 2019 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.14.dev4

Python 2.7.15+ (default, Jul  9 2019, 16:51:35)
[GCC 7.4.0]

Linux revest 5.0.0-1020-azure #21~18.04.1-Ubuntu SMP Fri Sep 13 14:10:02 UTC 2019 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.9.0
    Python module py2neo: 3.1.2
    Python module sqlalchemy: 1.3.8
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: 5.1.0
    Python module MySQLdb: missing
    Python module dbus: 1.2.6
    Python module matplotlib: missing
    Python module bottle: 0.12.17

root@revest:~/createscans# pip install matplotlib
Requirement already satisfied: matplotlib in /usr/local/lib/python2.7/dist-packages
```

**Comment by p-l-** [comment]
This has been fixed (weirdly, in an unrelated commit with an unrelated message: d42684a3b9d1e1134f59057729b098d40be618b5).
Please reopen if that is not the case.
