### ISSUE TITLE
GEOIP WARNING!!!!!!!!!!

### ISSUE THREAD

**Issue by linusien** [cea-sec/ivre#922]
apparently it is no longer possible to retrieve the geoip files because the site requires an account.
how to do it?

`sudo ivre ipdata --download
Downloading https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz to /home/thor/.local/share/ivre/geoip/GeoLite2-Country.tar.gz: Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 88, in <module>
    main()
  File "/usr/local/bin/ivre", line 60, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/home/thor/.local/lib/python2.7/site-packages/ivre/tools/ipdata.py", line 57, in main
    geoiputils.download_all(verbose=not args.quiet)
  File "/home/thor/.local/lib/python2.7/site-packages/ivre/geoiputils.py", line 154, in download_all
    udesc = opener.open(url)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1248, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1205, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>
`

**Comment by p-l-** [comment]
You should probably get an account (and update to ivre current development version, or wait for the next release which should happen during the next few days).

**Comment by linusien** [comment]
ok because modifying the program I couldn't do it

**Comment by linusien** [comment]
or download this BGP.csv
