### ISSUE TITLE
Issues while importing zgrab2 scan data

### ISSUE THREAD

**Issue by mfaizq** [cea-sec/ivre#950]
### IVRE Version

```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2019 Pierre LALET <pierre.lalet@cea.fr>
Version 0.9.14.dev127

Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0]

Linux f272407858e9 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64

Dependencies:
    Python module Crypto: 2.6.1
    Python module pymongo: 3.7.1
    Python module py2neo: missing
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module krbV: missing
    Python module PIL: 5.4.1
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.15
    Python module OpenSSL: missing
    Python module tinydb: missing
```

### Summary

Issues while importing zgrab2 results. I get below (under Actual Behaviour) results when importing results from a shared directory which has one masscan XML file and two zgrab2 JSON files. 

### Expected behavior
The scan files should be imported

### Actual behavior

```
root@f272407858e9:/# ivre scan2db -r -s MySource -c MyCategory /ivre-share/
WARNING:ivre:Exception (file '/ivre-share/zgrab2_80_20200604.json')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/scan2db.py", line 109, in main
    masscan_probes=args.masscan_probes, callback=callback,
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1622, in store_scan
    return store_scan_function(fname, filehash=scanid, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1783, in store_scan_json_zgrab
    host['start_time'] = rec.pop('timestamp')
KeyError: 'timestamp'
0 results imported.
root@f272407858e9:/# 

```
### How to reproduce

Use Vagrant docker file and add zgrab2 and masscan files to ivre-share directory and try to import results. 

### More
I have also attached the results whichI got when importing the files. The masscan import was successful with minor warnings and info messages. No errors or successful import messages for zgrab2 files. 

[ivre_log.txt](https://github.com/cea-sec/ivre/files/4741597/ivre_log.txt)

**Comment by p-l-** [comment]
Hi,

Could you provide a sample file?

**Comment by mfaizq** [comment]
[sample_443.json.zip](https://github.com/cea-sec/ivre/files/4745475/sample_443.json.zip)
Here is sample data. I kept only first 2000 lines. The original files are 1.67 GB uncompressed and 300+ MB compressed.

**Comment by p-l-** [comment]
This sample file works fine for me. Can you try with a more recent version? ZGrab2 support is quite recent.

**Comment by mfaizq** [comment]
Thank you. I tried with the new version and import was successful. Other than few minor warning messages there were no issues. 
Also, in case anyone has problems in building from source, I used pip3 to install - 

`pip3 install git+git://github.com/cea-sec/ivre@master`

Using python3 you can avoid some encoding/ascii errors during imports.

**Comment by p-l-** [comment]
@mfaizq if you have samples that work with Python 3 but not with Python 2, please report them, that is a bug that should be fixed!
